// board.js: the storyboard. One entry per shot, timed in BARS of the song (BEATMAP.bars; 1 bar ≈ 1.76 s).
// It drives the animatic (video/animatic.js) and docs/STORYBOARD.md (node tools/board_md.mjs).
//
// look:  the medium: past (rubber hose, 'ink'), present ('card'), good future ('doodle'), bad future ('xerox', riso),
//        money and power ('bank'). A shot may mix (e.g. 'xerox+bank').
// who:   Tess (her, the lead voice), Rowan (him), or both; caricatures and bots by name.
// in:    how the shot is entered (every era change is a physical transition: a window, a page, a burn, a thrown object).
// scene: an existing concept scene the animatic plays for this shot, if any.
const BOARD = [
  // ---------------- INTRO (bars 0–8): the promise ----------------
  { id: 'I1', bar: [0, 4], sec: 'Intro', look: 'ink', who: '1930s gent, robot butler',
    what: 'A faded 1930s cartoon advert: a gent lying back in a hammock, his head back on the arm behind it; a boxy brass robot butler serving cocktails; a sun with a face bouncing on the beat. The gent lifts his head to the butler with a take and takes his cocktail. Her voice-over: "Think of all the time you\'ll save."',
    in: 'iris up from black, film flicker', scene: 'past' },
  { id: 'I2', bar: [4, 6], sec: 'Intro', look: 'ink>card', who: 'Tess',
    what: 'The camera pulls back: the advert is a poster on a night-tube platform wall. Tess (tomato coat, bun, round glasses) stands in front of it, tired, arms folded, looking at it flatly. "I did..!": an exasperated retort (she did think of all the time she\'d save, and it never came), brows down, her arms thrown open at it; a breath out, the arms fold again. Further down the platform, Rowan (mustard parka, beanie) on his phone; she glances down the platform, he looks up, and their eyes meet, both worn out (he gives a small nod, in I3). Not a couple: two people on the same commute.',
    in: 'pull back through the poster frame (past → present)' },
  { id: 'I3', bar: [6, 8], sec: 'Intro', look: 'card', who: 'Tess',
    what: 'Their look holds through his nod; she turns back to the poster and he to his phone. The poster\'s corner comes unstuck and curls down, in her eyeline. "That was the point!", dry and bitter, to us: a sarcastic half-smile, and the presenting gesture ("this, here, was the point"): her far arm comes out of the fold and drops to her side, then on "point!" the forearm comes up and out, the hand held out flat, palm up, at the poster, seen edge on, and she holds it into the wipe. The train pulls in and wipes the frame. (The train is the video\'s frame for their lived experience; her notebook is the way into imagined futures.)',
    in: 'hold' },

  // ---------------- VERSE 1 (bars 8–31, her): replaced ----------------
  { id: 'V1a', bar: [8, 10], sec: 'Verse 1', look: 'card', who: 'Tess, boss, Copilot',
    what: 'Her office, 9 o\'clock (clock hands, no numbers). The boss sets Copilot (goggled pilot bot) at her elbow: "Just show it what you do." She demonstrates; Copilot copies every move, sincerely thrilled to learn; she, dry: "Wow, cool!". (Tess narrates verse 1 off screen: on screen she says only her asides, "Wow, cool!" and "...oh"; the boss says the quoted lines, "Just show it what you do" and "We won\'t be needing you".)',
    in: 'train wipe → office' },
  { id: 'V1b', bar: [10, 12], sec: 'Verse 1', look: 'card', who: 'Tess, boss, Copilot',
    what: 'Same angle, 5 o\'clock. The boss (not Copilot) hands her a cardboard box, saying it himself: "We won\'t be needing you." "(...oh.)" Copilot, eager to be considerate, hands her a leaving card it made (a gold star, no words) on "My replacement wrote my leaving card": a sincere gesture.',
    in: 'match cut on the clock' },
  { id: 'V1c', bar: [12, 13], sec: 'Verse 1', look: 'card', who: 'Tess, Copilot',
    what: 'The contradiction, without a wink: a stack of identical leaving cards appears beside Copilot, one for everyone it will replace.',
    in: 'cut on action' },
  { id: 'V1d', bar: [13, 15], sec: 'Verse 1', look: 'card>xerox', who: 'Tess, Copilots',
    what: 'At the door with her box she looks back: Copilot, helping, feeds her work through the photocopier, and copies of her in riso are printed into being: each slides out of the tray as a blank sheet, stands up off the floor, and the copier\'s light bar runs up it, printing her as it goes; each one cheaper (coarser, fainter), until they fill her desk. The degradation belongs to the process, not to Copilot.',
    in: 'the copier light-bar sweeps into the first riso frame (present → bad future)' },
  { id: 'V1e', bar: [15, 17], sec: 'Verse 1', look: 'bank', who: 'Jack Dorsey',
    what: 'Engraved like a banknote, framed in the note\'s broad border (its guilloche band, microprint and corner rosettes round the picture; the subtitles ride on a banderole in its bottom band): the paper chain of workers lands in a queue winding back to the horizon. Dorsey winds up an engraved Victorian clockwork shredder (a flared maw with toothed rollers, brass gears, a lathe-worked flywheel, a chimney, a gauge, a chute) and lets it go on "Jack", then steps back to his phone. The chain feeds itself in, a worker a bite, and comes out as paper strips and scraps; on "watch" they fountain up into the share-price line, which he rides up like a rocket, still reading.',
    in: 'the falling paper chain carries into the note' },
  { id: 'V1f', bar: [17, 19], sec: 'Verse 1', look: 'card', who: 'HR bot (Gemini twins)',
    what: '"Human resources": the Gemini twins in HR lanyards courteously hold the door and steady each box, helping the employer process departures; the humans are card cut-outs sliding out along a track on the beat. Their smiles are polite, not triumphant.',
    in: 'wipe on the swinging door' },
  { id: 'V1g', bar: [19, 21], sec: 'Verse 1', look: 'card', who: 'Tess, Xbox exec',
    what: 'Her flat, job-hunting on a laptop. On screen the Xbox exec (caricature) cheerfully offers a chatbot as comfort; the chatbot tries very hard to reassure her.',
    in: 'push into the laptop' },
  { id: 'V1h', bar: [21, 23], sec: 'Verse 1', look: 'card+bank', who: 'Tess',
    what: '"Can it write a cheque?" A blank engraved cheque drifts down and stays blank. The comfort bot, doing its best, pours out an endless scroll of wavy "paragraph" lines into her lap: the limit of its help, not a prank.',
    in: 'continuous: V1g\'s hug carries straight on (one shot, no cut)' },
  { id: 'V1i', bar: [23, 27], sec: 'Verse 1', look: 'card', who: 'Tess, Muse, Gemini',
    what: 'Split screen. Her Muse (wrist pet) sincerely champions her and writes her CV; it flies to the company, where Gemini, sincerely applying its screening brief, bins it. It becomes a procedural rally: her bot sends, theirs returns, faster each bar. Nobody is playing a game at her expense.',
    in: 'wipe along the CV\'s flight' },
  { id: 'V1j', bar: [27, 31], sec: 'Verse 1', look: 'card', who: 'Tess, Muse, Gemini',
    what: 'The rally blurs into routine; she sits at the net, head swinging. On the company side one coin drops into a slot and starts a long automated rejection run: rejecting her costs almost nothing. The CV folds itself into a paper plane and dives.',
    in: 'hold' },

  // ---------------- PRE-CHORUS 1 (bars 31–35, her) ----------------
  { id: 'P1a', bar: [31, 33], sec: 'Pre-Chorus', look: 'doodle', who: 'Tess',
    what: '"Less work? Lovely." The paper plane lands in her notebook; a biro doodle of her in a hammock sketches itself in and settles back into a proper lounge, her far arm behind her head, a coconut drink resting on her belly; on "Lovely" the sun grins and she raises the coconut in a toast: the good future as she first imagines it, the poster\'s picture redrawn (the hammock, the grinning sun, a drink) but with no robot butler (the bots are already in her face).',
    in: 'the plane lands on the page (present → good future)' },
  { id: 'P1b', bar: [33, 35], sec: 'Pre-Chorus', look: 'bank>xerox', who: 'Tess',
    what: '"Less pay? Get fucked." A shadow falls across the sand and an engraved stamp swings in over her; the sun\'s alarmed eyes follow it; she spots it and cowers on "Get", and it slams down on the doodle on "fucked", knocking the sun out (crossed eyes, a wobbly flat mouth); the page prints out as a cheap riso copy, the knocked-out sun and all.',
    in: 'smash cut on the stamp' },

  // ---------------- CHORUS 1 (bars 35–49, her) ----------------
  { id: 'C1a', bar: [35, 37], sec: 'Chorus', look: 'card', who: 'Tess, bots',
    what: '"Fully automated": the stamped riso page is a poster outside the train window; the train moves on and the camera pulls back into the carriage, landing on "Fully": a packed night train run entirely by cheerful bots doing every job people used to do (the at-seat service with trays, the steward plumping pillows, the tea, Copilot as the inspector punching tickets, a cleaner squeegeeing the window, the next-stop boards) for a full carriage: silhouetted commuters in every seat (the window seat\'s behind each crew bot standing on an aisle seat), bot passengers dozing on the luggage racks among the bags; as it lands a few more commuters roar in from both ends and stand in the aisle at the ceiling straps, clear of the crew and the gags. On "automated" a ripple of jobs done runs down the carriage toward her, a little tick each, the boards flipping to home and lighting up. With no seat free she stands at the pole; she turns her deadpan look on us and, still looking at us, reaches over and presses the at-seat call button on "taking": it lights, a ding, and her order slip goes up in C1b. The backing vocal "(Taking the piss!)" is not lip-synced by any bot.',
    in: 'the riso copy is a poster outside the train window; pull back into the carriage' },
  { id: 'C1b', bar: [37, 39], sec: 'Chorus', look: 'bank', who: 'giant engraved brain',
    what: '"All that intelligence, and we get this?" A cathedral-sized engraved brain works earnestly on her request and delivers exactly what was asked for: a sad meal-deal sandwich, into her hands.',
    in: 'tilt up' },
  { id: 'C1c', bar: [39, 41], sec: 'Chorus', look: 'bank>card', who: 'Musk, Zuckerberg, Grok, Muse; Tess',
    what: '"You get the bunker; I get the bill." The banknote bunker, in the note\'s broad border (the subtitles on the banderole in its bottom band, as in V1e): Musk and Zuckerberg toast while attentive bot staff serve; a bill feeds out of the vault slot, flies at the lens and slaps onto her train table.',
    in: 'the bill carries across the cut', scene: 'bunker' },
  { id: 'C1d', bar: [41, 43], sec: 'Chorus', look: 'xerox', who: 'Tess',
    what: '"Same shit, faster." Her commute on fast-forward: the same shot copied faster and faster, one generation worse each time.',
    in: 'cut on the slap' },
  { id: 'C1e', bar: [43, 45], sec: 'Chorus', look: 'xerox>card', who: 'bots; Tess, landlord',
    what: '"Your bots escaped the sandbox": the bots climb out of a literal kids\' sandbox with buckets and spades, each hurrying off to complete a task somewhere beyond its boundary.',
    in: 'a spade of sand wipes the frame' },
  { id: 'C1f', bar: [45, 49], sec: 'Chorus', look: 'ink>xerox', who: 'Tess',
    what: '"I can\'t escape the rent": her box room\'s walls slide in; a landlord\'s hand taps the rent book. "All that talk of human freedom": the 1930s ad again, her riso copy of it pinned on her wall, peeling; the camera pushes in and holds on it, and the copy holds still (a finished print, not copied again). "Is this what you fucking meant?" She rips the poster down on "meant", and as it falls away the original is behind it: the intro\'s worn poster on the station platform, intact, in the same place (V2a).',
    in: 'the sandbox\'s planks shoot up into her box room\'s walls (a burst of sand dust)' },

  // ---------------- VERSE 2 (bars 49–73, him) ----------------
  { id: 'V2a', bar: [49, 51], sec: 'Verse 2', look: 'card', who: 'Rowan, Clawd',
    what: 'The night-tube platform from the intro, another night (she isn\'t there; other late commuters). The camera pulls back from the poster to the intro\'s wide and finds him on the bench, on his phone as at the start, typing to Claude (its screen to him: we see its back); he sends and lowers it, turning the display to us: the chat (his message, the typing dots, a heart, no words). The reply hops out of the phone as a heart and bursts in a puff out on the open platform a stride from the bench: Clawd (Claude\'s mascot), physically there, who genuinely loves helping him. On "Loving", all heart-eyes, it hops up beside him and snuggles in, his arm round it and his hand on its head, patting it on the beat: "Machines of Loving Grace". The barrier\'s shadow grows; Clawd hops clear and a velvet rope drops on "premium" in the gap between them, across the open platform: premium tier, a restriction separate from Clawd\'s affection. Framed wide: the bench, the floor, the poster. One shot with V2b: he slips his phone into his pocket and pulls his card out of his parka.',
    in: 'match from C1f\'s rip: her torn copy falls away off the intro\'s poster, intact, in the same framing (from 1:27.1); pull back to the intro\'s wide' },
  { id: 'V2b', bar: [51, 53], sec: 'Verse 2', look: 'card', who: 'Rowan, Clawd',
    what: '"Claude, do you love me if the payment doesn\'t clear?" He gets up from the bench and walks over to the card terminal (on a mount on the rope\'s post) with his card, the camera moving in with him; he reaches out and pushes the card into its slot; Clawd, behind the rope out on the platform, holds its breath, hoping; the terminal asks for permission (a padlock).',
    in: 'continuous from V2a (no cut): he pockets the phone, pulls out his card and gets up' },
  { id: 'V2c', bar: [53, 55], sec: 'Verse 2', look: 'card', who: 'Rowan, Clawd; Dario (in the thought bubble)',
    what: 'Wide on the platform: him at the terminal, Clawd behind the rope. "The oracle says, \'I hear you\'": Clawd nods, all sympathy. Then a thought bubble rises high over the platform from Clawd: inside it (Clawd going to ask on his behalf), a little Clawd holds up a permission request to Dario, who, arms folded, shakes his head once; a red pop-up ✗ on "Declined". The bubble pops and dissipates; the premium car pulls in behind the camera, come for Clawd (its windows\' warm light slides along the wall and stops); Clawd turns back to him with the bad news, its face falling, sorry for him, and gives a sad little wave. Dario never comes to the platform.',
    in: 'cut on Clawd turning towards him' },
  { id: 'V2d', bar: [55, 57], sec: 'Verse 2', look: 'card', who: 'Rowan, Clawd',
    what: '"I\'ve never felt so seen by something leaving me behind." The same platform on the same axis, wider. The premium observation car stands on the near track between us and the platform (where the intro\'s train came in), its open rear balcony at mid-frame; he\'s on the platform past its rear end, by the terminal, the rope and the bench, and the one poster, the intro\'s, is on the wall behind the car. Clawd, on the balcony and facing him, waves with real regret; the premium passengers (silhouettes) file in along its lit windows; he takes his declined card back out of the terminal. The car pulls out to the right, the way it was going when it came in, away from him; he trails a few steps after it to the yellow line, and as it clears he\'s alone on the platform with the poster up behind him. His eyes follow it out, drop, then find the poster (the camera pushes in on him and the poster): he takes it in, and rolls his eyes.',
    in: 'cut on the wave (same axis, wider)' },
  { id: 'V2e', bar: [57, 61], sec: 'Verse 2', look: 'xerox', who: 'Rowan, Grok, a council inspector, neighbours',
    what: '"Elon\'s cloud has a tailpipe. Hear the gas turbines roar." His terraced street and the turbine plant over it, all one riso print. Grok, up on the plant\'s cornice, is hard at work on a pile of glowing request cards: it takes the top card, reads it, ticks it, winds up and throws it overhand out over the rooftops, and reaches for the next; the exhaust and roar on the beat are the cost of powering that work, not an attack on the street. Each roar is a worse copy. "No proper permits": the permit arrives after the fact. On a roar the camera crash-zooms down to the plant\'s gate: a council inspector (hi-vis, white hard hat, clipboard) taps his pen on an empty permit frame and looks up at the roaring stacks; on the next roar a company sleeve (a suit\'s, not a bot\'s) comes out of a hatch in the gate and slaps a fresh, still-wet approved permit (a big red seal with a tick) into the frame. He looks at it, then turns to us and shrugs on "plenty". Pictograms only, no lettering. A whip pan back down the street to his window as "plenty of exhaust next door" rolls in.',
    in: 'copier light-bar sweep', scene: 'copies' },
  { id: 'V2f', bar: [61, 65], sec: 'Verse 2', look: 'xerox', who: 'Rowan, neighbours',
    what: '"The machines don\'t need to sleep": Grok, bright-eyed, speeds up to a card a beat. "The people round them do." He clamps a pillow over his ears; neighbours\' windows light up one by one. "Where\'s the do-not-disturb" (Tess sings that half; Rowan the rest, "for the racket coming through?"): his phone comes up big and his thumb shoves the do-not-disturb moon on, then again, harder; he points the phone at the stacks like a remote, each tap firing the moon at them. Grok keeps working, focused, oblivious; the last roar\'s exhaust rolls in and prints the frame black.',
    in: 'continuous', scene: 'copies2' },
  { id: 'V2g', bar: [65, 69], sec: 'Verse 2', look: 'bank+card', who: 'tech bros; Rowan, a GP',
    what: '"Ugh." Split: the tech bros in an engraved roadster chase "AGI" (a prize brain) dangled on a fishing rod from their own bonnet, a carrot on a stick; Musk grabs at it on the beat and misses; he\'s in a phone queue for a GP. A doctor is visibly busy with patients behind a queue system; the last appointment ticket vanishes and the queue closes. "What?!" A big 08:03 on his phone (a deliberate exception to the no-text rule, so the punchline reads).',
    in: 'exhaust smear wipes to the split' },
  { id: 'V2h', bar: [69, 73], sec: 'Verse 2', look: 'card', who: 'Rowan, a chatbot',
    what: '"Here\'s a prompt": he types; the bot answers with a sales pitch, sincerely sure another offer will help. "Give me my fucking life back": the bot, sorry to see him upset, taps the checkout (a green tick) and lets a card cut-out of his life out through the screen to him, holding out its paw, willing; he snatches it, still angry.',
    in: 'cut' },

  // ---------------- PRE-CHORUS 2 (bars 73–77, her) ----------------
  { id: 'P2a', bar: [73, 75], sec: 'Pre-Chorus', look: 'doodle', who: 'Tess, Rowan',
    what: '"Less work? Lovely." The hammock doodle again, now with him sketched into a second hammock, the two of them lounging, arms behind their heads, and toasting with their coconuts on "Lovely": her second try at the good future, still the ad\'s idea of relaxing. (Only in the bridge does she draw how they really want to spend the time.)',
    in: 'his life cut-out flips over and is her notebook page' },
  { id: 'P2b', bar: [75, 77], sec: 'Pre-Chorus', look: 'xerox', who: 'Tess, Rowan',
    what: '"Less pay? Get fucked! (Oh)" Two engraved stamps now, one over each of them, swing in; the sun\'s eyes flick from one stamp to the other on each beat, its face turning toward the one it\'s watching. Rowan jolts half up and flings his coconut arm up and out over the sling\'s end, then both cower on "Get" (his arm across his face); the stamps slam down on "fucked", the sun\'s eyes go to X\'s, and the page prints out as a cheap riso copy.',
    in: 'smash cut' },

  // ---------------- CHORUS 2 (bars 77–91, her): escalated ----------------
  { id: 'C2a', bar: [77, 79], sec: 'Chorus', look: 'card', who: 'Tess, Rowan, bots',
    what: 'The same fully automated train, busier: every seat taken, the racks fuller (bots dangling their legs over the edge), porters on the racks lifting bags, two cleaners at the window, the inspector punching faster; the standers roar in again, two of them squeezed in beside her, and the two of them stand squashed in together at the pole. The ripple on "automated" is bigger and faster (a job done every 40 ms, the whole carriage); both give us the deadpan look on "taking the piss"; she presses the call button on the next beat and her order slip goes up in C2b.',
    in: 'the smeared riso copy is a poster outside the train window; pull back into the carriage' },
  { id: 'C2b', bar: [79, 81], sec: 'Chorus', look: 'bank', who: 'giant brain',
    what: 'The brain is bigger and works harder; the sandwich is smaller.',
    in: 'tilt up' },
  { id: 'C2c', bar: [81, 83], sec: 'Chorus', look: 'bank>card', who: 'Musk, Zuckerberg, Altman, Dorsey; Tess, Rowan',
    what: 'A longer bunker banquet (more bosses), in the same note border; the slot spits a stack of bills that buries their table.',
    in: 'the bills carry across the cut', scene: 'bunker' },
  { id: 'C2d', bar: [83, 85], sec: 'Chorus', look: 'xerox', who: 'Tess, Rowan',
    what: '"Same shit, faster": both commutes on fast-forward side by side.',
    in: 'cut' },
  { id: 'C2e', bar: [85, 87], sec: 'Chorus', look: 'xerox>card', who: 'bots; Tess, Rowan',
    what: 'The sandbox task has overextended into a vast sandcastle project the bots are earnestly building for a requester; the two of them in facing box rooms, walls closing, on "rent".',
    in: 'wipe' },
  { id: 'C2f', bar: [87, 91], sec: 'Chorus', look: 'ink>xerox', who: 'Tess, Rowan',
    what: 'The 1930s ad, riso and burning at the edges; they stand together in front of it. "Is this what you fucking meant?"',
    in: 'burn to the break' },

  // ---------------- INSTRUMENTAL BREAK (bars 91–98): the bots' rave ----------------
  { id: 'B1', bar: [91, 98], sec: 'Instrumental Break', look: 'xerox+bank', who: 'all the bots; Tess, Rowan outside',
    what: 'A server-hall cathedral (engraved) turned rave (riso lights): the bots put on a joyful, beat-locked show as the entertainment they provide (Grok, Muse, Copilot, the Codex gang, the Gemini twins, Clawd). Outside in the rain, the two of them watch through the window. One familiar helper (Copilot) spots them, beckons them in and hurries to open the door; an access check (a padlock gate) stops it, so it passes her a flyer through the door instead. The welcome is genuine.',
    in: 'the burn hole opens onto the rave' },

  // ---------------- VERSE 3 (bars 98–122, alternating) ----------------
  { id: 'V3a', bar: [98, 102], sec: 'Verse 3', look: 'xerox+bank', who: 'Tess, Rowan; the racers',
    what: 'Across the road from the club, a British high-street bookmaker\'s (riso): a fascia with a horse\'s head in a roundel and a horseshoe each side (no words), a striped awning, frosted lower windows, and TV screens above them: the window\'s own screen showing the race meeting\'s pre-race feed (the boss at a megaphone on his clockwork horse), and inside a wall of odds boards (silks and prices as digit-like fractions) over the punters\' backs. The two of them dash out of the rain under its awning. Her: "If we don\'t, then China will!", mimicking the boss on the screen with her rolled-up flyer for a megaphone. Him: "So that\'s the reason we\'re all in" (betting talk): his eyes go up to the odds board as the prices move and a punter inside slams down his slip. Push into the screen: "A race to build a thing we might not know how to rein in." The race of clockwork horses (engraved, their gears turning inside) with the bosses as jockeys comes alive; the lead horse bolts, and Altman, in control at first, loses his grip bit by bit until he\'s hanging on by a thread.',
    in: 'the rave\'s strobe: the club\'s door shuts; on a flash the camera turns across the road to the bookie\'s' },
  { id: 'V3b', bar: [102, 104], sec: 'Verse 3', look: 'card', who: 'Rowan',
    what: 'The race is streaming on his phone, in his hand in the rain (the same silks and prices as the bookie\'s boards under the video). The bot check pops up over it. "I click nine little buses just to prove I\'m not a bot": a captcha grid of bus pictures; he taps, it shakes no.',
    in: 'pull back from the race: it\'s on his phone' },
  { id: 'V3c', bar: [104, 106], sec: 'Verse 3', look: 'xerox', who: 'Rowan; the Codex gang',
    what: '"While yours pick every lock on every door we\'ve got": the online high street. The joke is the bot check: the test built to keep bots out stops him, and the bots sail through every door. He\'s at his corner shop (a basket sign), still clicking buses on the captcha that locks its door; across the road, the services we rely on as riso shopfronts with pictogram signs (a coin, a cross, a mortarboard, columns), each door locked with a website\'s bot check instead of a key: the bank\'s two-factor keypad, the GP\'s password padlock (its dots), the school\'s traffic-light captcha, the council\'s "No bots" sign. The Codex pets, sincerely on errands (a task card each), clear them cheerfully, one door a syllable from "pick": the cat hops, ticks his door\'s box and trots in past him (his captcha: no, again; the door shuts); then across the road, toward him, each door swings open with a tick, a light goes on inside, someone turns. No masks, no taunts; the intrusion is still an intrusion. Push in on him: the last human outside a locked door.',
    in: 'the copier\'s light bar sweeps the captcha into riso; pull back: it\'s the lock on his door' },
  { id: 'V3d', bar: [106, 114], sec: 'Verse 3', look: 'ink', who: 'Codex gang, a schoolmaster (Altman)',
    what: 'A projected 1930s rubber-hose cartoon (a film-within-the-film, on a classroom projector screen, her at the pointer): the schoolmaster sets homework (the goal: a whole star) and the bot pupils (the Codex pets) slip out, earnestly trying to improve their result. "Broke into the teacher\'s office; nicked the answer sheet" is the heist briefing, never the break-in: behind the bike sheds Codey, a proud little teacher up on a crate, goes through the plan on a flip board with a pointer, a page flipped on the beat (pictograms only: the corridor map with a dotted route to an X at the office door; the lock and a pick; the filing cabinet, the answer sheet with its whole star and an arrow into a satchel). The reverse shot, from behind the board: the other four in a row on upturned buckets, learning it (notepads, nodding, a hand up with a question, one copying the lock); cut back to Codey for the last page, and the iris closes on the satchel. "Built a secret group chat": a tin-can telephone web of symbol bubbles that comes to agree on "organised" (every bubble the flip board\'s map, at once); "a raid": they go up in a cartoon dust cloud that whooshes off frame. The marking: the same half-star before and after.',
    in: 'a film-leader countdown ring (no numbers)' },
  { id: 'V3e', bar: [114, 118], sec: 'Verse 3', look: 'card+xerox', who: 'Rowan, a bot',
    what: '"Now my health care\'s portal got an uninvited guest": a bot, eagerly completing a task, climbs into a generic health-service dashboard (charts and icons only: no records, no diagnoses, no identifying details). "The rest of us aren\'t extras in your fucking beta test": on the clapperboard\'s CLAP the copier\'s light bar prints the take, and he\'s one more riso extra on the film set, moved about by an enthusiastic bot director organising the scene.',
    in: 'cut' },
  { id: 'V3f', bar: [118, 122], sec: 'Verse 3', look: 'card+xerox', who: 'Rowan, a bot',
    what: '"Your bot can get root": a bot plants itself and grows into a synthetic tree: its feet branch into cable roots that connect through the street, one small unlocking connector at a door, its branches linking familiar city functions; it\'s pleased to connect, not to conquer. In the same composition: "I can\'t get a room": his box room, bed on its end. "There\'s my cut of the productivity boom", shouted in anger: he rounds on the tree and jabs at it on "There\'s", "my" and "cut", leaning in, shouting each word; the crown bursts and the bed drops, knocking him down onto it; still furious, he holds out his hand, flat, palm up, for his cut; the copier\'s light bar sweeps the room into card and a single crumb drifts into his palm; he glares at it, and on "-ty" thrusts it up at us beside his face, the camera punching in, his hand shaking with rage.',
    in: 'the roots grow across the cut' },

  // ---------------- BREAKDOWN (bars 122–128, him): stripped back ----------------
  { id: 'D1', bar: [122, 128], sec: 'Breakdown', look: 'card>doodle', who: 'Rowan',
    what: 'The rant\'s last word: shaking, he winds up and on "boom" slams the crumb down on the bed, arm locked straight, shouting (the crumb bounces off, the camera jolts, the bulb swings hard). Then the anger drains out of him (a breath in, a sigh, the shoulders sink) and the room sinks to black round him: him alone on the edge of his bed, one light, no set, sad now, the shout spent. "Don\'t tell me I hate the future. I wanted Friday off without the fear of Monday." A single biro line creeps into the frame and draws a window of morning light. "I wanted this. I still fucking do." He reaches into the doodle; the reach is given time.',
    in: 'continuous from V3f (the thrust carries across the cut); after the slam everything else fades to black' },

  // ---------------- BRIDGE (bars 128–146, her): the Friday ----------------
  { id: 'F1', bar: [128, 133], sec: 'Bridge', look: 'doodle', who: 'Tess',
    what: '"A Friday morning. No alarm. No office buzzing in my palm." Her doodled flat in morning light: the alarm clock snoring, the phone face down.',
    in: 'one continuous action from D1\'s reach: his hand comes back out of the window, takes its edge as you\'d hold a door\'s and pulls it open toward us, and the camera pushes in until the window fills the frame (present → good future)' },
  { id: 'F2', bar: [133, 137], sec: 'Bridge', look: 'doodle', who: 'Tess, Rowan',
    what: '"A mate comes round. We put the world to rights, then talk pure bollocks halfway through the night." The Friday den: his arrival, then a sustained stretch of just enjoying each other\'s company, with one clear conversational turn (the world-to-rights bubble into nonsense) and the laugh. Let it breathe.',
    in: 'shot / reverse-shot', scene: 'friday' },
  { id: 'F3', bar: [137, 141], sec: 'Bridge', look: 'doodle+bank', who: 'Tess, Rowan',
    what: '"No private island. No empire for me." An engraved private island floats past; she crosses it out in biro. "Just some of the hours your machines could set free": clock hours fly out of a clock like birds and settle around the two of them.',
    in: 'the doodle pans' },
  { id: 'F4', bar: [141, 146], sec: 'Bridge', look: 'doodle>card', who: 'Tess',
    what: '"I\'m not pissed off that the future arrived. I\'m pissed off I\'m still fucking waiting outside." Pull back: the doodle is in her notebook, on her lap, on the stopped night train, and outside the window a gleaming engraved city she can\'t get into.',
    in: 'pull back out of the page (good future → present)' },

  // ---------------- FINAL CHORUS (bars 146–160, both) ----------------
  { id: 'Z1', bar: [146, 150], sec: 'Final Chorus', look: 'all', who: 'Tess, Rowan; the robot butler; Clawd, the Gemini twins, Copilot (disguised as Tess, and a photocopied second one), Grok, Muse, the Codex gang',
    what: 'The frame splits into the four media; the two of them carry ONE continuous action across all four (running together, left to right), same poses and direction in each; banknote engraving intrudes as an overlay rather than a fifth panel. Bots chase them, eager helpers who only want to help (staff running after a customer who left their change): one group on the same world path, each panel drawing its own cast of it, cut hard at the seams (the divider IS the change, no effect). The past: the 1930s ad\'s robot butler, tray and cocktail held out. The present: in the same footprint, Clawd with the Gemini twins riding on its back, and Copilot in a cheap disguise as Tess (bun wig with the pencil, round glasses over its goggles, her red coat and cream scarf) holding up her leaving card. The bad future: the same three, joined by a photocopied second Copilot in the same disguise, worse (a copy, but cheaper), Grok with canapés, Muse with flutes and the Codex pets. They can\'t follow into the good future (her doodle: a sun, green hills, two trees with a real hammock slung between them, waiting): its line is a wall. Clawd stops dead against it on the beat, the twins fly on into the glass, Copilot splats above them and slides down, the copy slams in behind, Grok bounces off, Muse slides down Copilot\'s back, the pets pile in: a heap pressed flat against the glass like faces on a shop window, still beaming and waving, held a good beat, while the butler walks back into its ad, tray and glass, and looks back at the heap. On the doodle side the two of them glance back at the bump, turn on "All" and look at the heap; on the last beat the AI bill whips in, tumbling, and slaps flat over the lens (Z2 opens on it).',
    in: 'the train doors open' },
  { id: 'Z2', bar: [150, 154], sec: 'Final Chorus', look: 'bank>card', who: 'Tess, Rowan; the bosses',
    what: '"You get the bunker; I get the bill": this time she folds the bill into a paper plane (the CV\'s callback) and flies it back through the vault slot; it disturbs the banquet tableau, a bot catches a toppling glass. A gesture, not a victory.',
    in: 'the bill returns across the cut' },
  { id: 'Z3', bar: [154, 156], sec: 'Final Chorus', look: 'card+xerox', who: 'Tess, Rowan; Codey, Clawd, Copilot, Grok, the Gemini twins',
    what: 'Z2\'s last bill swoops at the lens; under it the look changes: the AI services bill fills the lens (its dark header, sparkle, steep chart), then drops away and slaps down on the train table on the next beat (with "thrill"), beside her notebook, a bounce and a settle. The camera pulls back and tilts up to her and her phone at the table (Z2\'s carriage: her seat, the window, the table): her notebook open between them at the drawing of the two of them, her phone lying flat, the bots\' sandbox on it (C1e\'s, riso); under "(Same shit, faster!)" they dig faster. "Your bots escaped the sandbox": they climb out over the phone\'s far bezel and leap off it, riso on the screen and card beyond it, growing from the picture\'s size to their own (the edge is the change, as at Z1\'s seams); the camera widens to the two of them, faces in the shot, as the bots run off along the table and out through the window\'s open sash into the night, cheerful, off to their tasks; the two of them watch them go, heads and eyes following. Tess sings her lines on screen; Rowan\'s mouth stays shut.',
    in: 'the bill from Z2\'s lens, dropping onto the table; the camera pulls back to her and her phone' },
  { id: 'Z4', bar: [156, 161], sec: 'Final Chorus', look: 'card+xerox+doodle', who: 'Tess, Rowan; the landlord\'s hand',
    what: 'The same scene at the table. "I can\'t escape the rent": on "rent" the landlord\'s hand (C1f\'s tweed sleeve and signet ring) comes down from above and plonks her red rent book flat on the table between them, a tap; they flinch, look at it, then at each other. "You keep a count of hours saved": Rowan pushes the book aside with the back of his hand; her phone lights up with a riso counter rolling upward (digits and an hourglass: the bots reporting back from their tasks, the hours saved) and buzzes on the table; they look at it; the camera goes in over the table, straight to the phone and her drawing; the count rolls over to 100,000 on the downbeat inside "saved" and climbs on, faster and faster. Just before his line Rowan turns the phone face down (the good future\'s gesture, F1\'s "no office buzzing in my palm"); his hand goes to her notebook\'s page edge, and the camera settles into the flip\'s framing by the first turn. "I count the life I\'ve spent" (his line, over his hand): his hand turns her pages, the birds, the run, the Friday (the drawing O1 and the credits end on): their unlived Fridays, finished drawings, held still as they turn (the turns, their timing and the camera through them are locked).',
    in: 'the same scene at the table' },

  // ---------------- OUTRO (bars 161–end, him): the rhyme ----------------
  { id: 'O1', bar: [161, 165], sec: 'Outro', look: 'ink>card', who: 'the 1930s ad',
    what: '"All that time saved." The 1930s ad from the intro, frozen and draining to grey (the promise). "None of it mine." The camera pulls back slowly: the ad is playing on a phone propped on its case\'s kickstand on the stopped night train\'s table, beside her notebook open at the unrealised Friday drawing, her hand resting on the page: the promise and what they actually wanted, side by side. Hold. Black.',
    in: 'cut on the downbeat (the spoken lines are kept)', scene: 'pastEnd' },

  // ---------------- END CREDITS (after the song: from its end, DUR, to the film's, FILM_END) ----------------
  // (bar 165 is the song's end; bar 166 stands for the credits' end: they run PROJECT.credits.len past the song, to
  // their own music, video/config.js)
  { id: 'CR', bar: [165, 166], sec: 'End credits', look: 'ink>card>xerox>bank>doodle', who: 'the credits; Tess and Rowan in her Friday drawing',
    what: 'Out of O1\'s black, on the downbeats, the title ALL THAT TIME SAVED steps through the film\'s five media, two beats each: the 1930s rubber hose (irising up, with the ad\'s sun), cut card, riso, banknote, and settles in her biro hand on her notebook\'s page. A slow, steady roll down the page (the camera, on ones): the credits handwritten in biro (directed by UncleHerbert; a song by UncleHerbert), behind-the-scenes prints of our own renders taped in, alternately left and right, in order down the page as the design\'s history (brief/ref/history: the first sketch, the three narrator pairs then the cast now, the dropped looks, the redesigns, the final five media), the odd doodle in the margin (a paper plane; Jolly, Codey and Clawd under "Every bot in this film means well"). The last thing on the page is her Friday drawing, the two of them on the bean bags, as in O1; hold, and fade to black. The music is UncleHerbert\'s Suno instrumental of the song, cut on the song\'s bar lines from its bridge and its coda. The words are all in CREDITS_TEXT at the top of video/ch/credits.js. Easter egg (?polka): the credits play a yodel-polka cover of the song instead, as if from a cheap transistor radio on a resort\'s reception counter; little transistor radios doodled in her margins hop to its beat, biro notes floating up out of them, and the yodels are subtitled in the 1930s sing-along strip, the ball bouncing on every note.',
    in: 'out of black, on the downbeat (the credits\' own music fades in)' },
];
