#!/usr/bin/env python3
"""usage_stats.py: how much Claude it took, for the end credits (the user: "tally Opus 5.5's usage, hours spent/tokens").

Reads Claude Code's own session logs for this project (~/.claude/projects/<project>/<session>.jsonl and its subagents'
transcripts, subagents/*.jsonl), as ccusage does: every API response logs its model and token usage; a response is
logged once per content block, so they're counted once per message id. Writes src/credits_usage.js (CREDITS_USAGE,
read by video/ch/credits.js) and prints a summary.

  tokens    input (uncached), output (thinking included), cache writes, cache reads, per model
  requests  API responses
  tools     tool calls
  agents    subagents launched (one transcript each)
  span      first to last logged event (days, hours)
  active    the main session's working time: the sum of the gaps between its logged events, a gap over IDLE counting as
            idle (the user away, asleep); agent_hours: the same summed over every subagent (they ran in parallel)

    .venv/bin/python tools/usage_stats.py        (re-run before a final render: the numbers keep growing)
"""
import glob, json, os, sys
from collections import defaultdict
from datetime import datetime

PROJ = os.path.expanduser('~/.claude/projects/' + os.path.abspath('.').replace('/', '-'))   # (Claude Code's folder for this project: run from its root)
OUT = 'src/credits_usage.js'
IDLE = 10 * 60   # s: a longer gap between logged events isn't work

def ts(s): return datetime.fromisoformat(s.replace('Z', '+00:00')).timestamp()

def scan(path):
    msgs, times, tools = {}, [], 0
    with open(path, 'rb') as f:
        for raw in f:
            if b'"timestamp"' not in raw: continue
            try: e = json.loads(raw)
            except Exception: continue
            t = e.get('timestamp')
            if t: times.append(ts(t))
            m = e.get('message') if isinstance(e.get('message'), dict) else None
            if not m or m.get('role') != 'assistant' or 'usage' not in m: continue
            mid = m.get('id') or e.get('uuid'); u = m['usage']
            if isinstance(m.get('content'), list): tools += sum(1 for c in m['content'] if isinstance(c, dict) and c.get('type') == 'tool_use')
            prev = msgs.get(mid)
            if prev is None or (u.get('output_tokens') or 0) >= (prev[1].get('output_tokens') or 0): msgs[mid] = (m.get('model') or '?', u)
    return msgs, sorted(times), tools

def active(times):
    return sum(b - a for a, b in zip(times, times[1:]) if b - a <= IDLE)

main = glob.glob(f'{PROJ}/*.jsonl'); subs = glob.glob(f'{PROJ}/*/subagents/*.jsonl')
tok = defaultdict(lambda: defaultdict(int)); req = defaultdict(int); tools = 0; t_all = []; main_active = 0; agent_active = 0
for i, p in enumerate(main + subs):
    msgs, times, tc = scan(p); tools += tc; t_all += times[:1] + times[-1:]
    if p in main: main_active += active(times)
    else: agent_active += active(times)
    for model, u in msgs.values():
        if model.startswith('<'): continue   # (synthetic entries)
        req[model] += 1; d = tok[model]
        d['input'] += u.get('input_tokens') or 0; d['output'] += u.get('output_tokens') or 0
        d['cache_write'] += u.get('cache_creation_input_tokens') or 0; d['cache_read'] += u.get('cache_read_input_tokens') or 0
        d['thinking'] += (u.get('output_tokens_details') or {}).get('thinking_tokens') or 0
    print(f'\r{i + 1}/{len(main) + len(subs)} transcripts', end='', file=sys.stderr)
print(file=sys.stderr)
t0, t1 = min(t_all), max(t_all)
tot = {k: sum(d[k] for d in tok.values()) for k in ('input', 'output', 'cache_write', 'cache_read', 'thinking')}
data = {
    'models': {m: {**dict(d), 'requests': req[m]} for m, d in tok.items()},
    'total': {**tot, 'all': tot['input'] + tot['output'] + tot['cache_write'] + tot['cache_read'], 'requests': sum(req.values())},
    'tools': tools, 'agents': len(subs),
    'start': datetime.fromtimestamp(t0).strftime('%Y-%m-%d %H:%M'), 'end': datetime.fromtimestamp(t1).strftime('%Y-%m-%d %H:%M'),
    'span_h': round((t1 - t0) / 3600, 1), 'active_h': round(main_active / 3600, 1), 'agent_h': round(agent_active / 3600, 1),
}
with open(OUT, 'w') as f:
    f.write('// credits_usage.js: generated by tools/usage_stats.py from Claude Code\'s session logs (do not edit; re-run it).\n')
    f.write('const CREDITS_USAGE = ' + json.dumps(data) + ';\n')
print(json.dumps(data, indent=1))
