"""voices.py: which voice actually sings each lyric line, measured from the vocal stem.

    .venv/bin/python tools/voices.py out/audio/stems/htdemucs/song/vocals.wav   (after tools/lyrics.py)

Adds to every line in assets/lyrics.json (and src/lyrics.js): voice ('F' or 'M', by timbre, overruled by a clearly
male pitch, deferring to the lyric sheet when the evidence is weak), voiceConf (how much closer the line is to that
voice than the other, 1 = no difference) and pitch (median Hz). The two voices are learnt
from sections whose singer label is certain (--female / --male section names). The labels in the lyrics say who SHOULD
sing; this says who DOES, which can differ in a generated song. A listener's corrections in --overrides win.
Caveat: the male singer's high register sounds like the female voice to the timbre model; only low pitch is reliable.
"""
import argparse, json
import numpy as np
import librosa

ap = argparse.ArgumentParser()
ap.add_argument('vocals')
ap.add_argument('--lyrics', default='assets/lyrics.json')
ap.add_argument('--js', default='src/lyrics.js')
ap.add_argument('--female', default='Verse 1')
ap.add_argument('--male', default='Breakdown,Outro')
ap.add_argument('--overrides', default='assets/voice_overrides.json', help='{sections: {name: F|M}, lines: {text prefix or start time: F|M|[F, word, M, ...]}}; what a listener heard beats the measurement')
a = ap.parse_args()

y, sr = librosa.load(a.vocals, sr=16000, mono=True)
hop = 256
M = librosa.feature.mfcc(y=y, sr=sr, n_mfcc=20, hop_length=hop)[1:]
rms = librosa.feature.rms(y=y, hop_length=hop)[0]
f0, vf, _ = librosa.pyin(y, fmin=70, fmax=500, sr=sr, frame_length=1024, hop_length=hop)
tt = librosa.times_like(rms, sr=sr, hop_length=hop)
loud = rms > np.percentile(rms, 40)
d = json.load(open(a.lyrics))


def feat(l):
    m = (tt >= l['start']) & (tt <= l['end']) & loud
    return M[:, m].mean(1) if m.sum() > 10 else None


fem, male = a.female.split(','), a.male.split(',')
F = np.mean([f for l in d['lines'] if l['section'] in fem and not l['backing'] and (f := feat(l)) is not None], 0)
Mm = np.mean([f for l in d['lines'] if l['section'] in male and not l['backing'] and (f := feat(l)) is not None], 0)
for l in d['lines']:
    f = feat(l)
    m = (tt >= l['start']) & (tt <= l['end']) & vf
    l['pitch'] = round(float(np.nanmedian(f0[m])), 1) if m.sum() > 5 else None
    if f is None:
        l['voice'], l['voiceConf'] = None, None
        continue
    dF, dM = float(np.linalg.norm(f - F)), float(np.linalg.norm(f - Mm))
    l['voice'], l['voiceConf'] = ('F', round(dM / dF, 2)) if dF < dM else ('M', round(dF / dM, 2))
    # pitch settles what timbre can't: a line centred below ~175 Hz is the male voice (hers sits at 200-380 Hz here)
    if l['pitch'] and l['pitch'] < 175 and l['voice'] == 'F':
        l['voice'], l['voiceConf'] = 'M', round(175 / l['pitch'], 2)
    # weak evidence (under 1.35x, pitch not decisive) defers to the lyric sheet's singer
    elif l['voiceConf'] < 1.35 and l['singer'] in ('F', 'M'):
        l['voice'] = l['singer']
import os
if os.path.exists(a.overrides):
    ov = json.load(open(a.overrides))
    used = set()
    for l in d['lines']:
        key = next((k for k in ov.get('lines', {}) if l['text'].startswith(k) or f"{l['start']:.2f}" == k), None)
        v = ov['lines'][key] if key else ov.get('sections', {}).get(l['section'])
        if key:
            used.add(key)
        if not v:
            continue
        l['heard'], l['voiceConf'] = True, None
        if isinstance(v, list):   # a split line: [voice, word index, voice, ...]
            n, wv, cur, k = len(l['text'].split()), [], v[0], 1
            for i in range(n):
                while k < len(v) and i >= v[k]:
                    cur, k = v[k + 1], k + 2
                wv.append(cur)
            l['wordVoice'], l['voice'] = wv, max(set(wv), key=wv.count)
        else:
            l['voice'] = v
            l.pop('wordVoice', None)
    for k in ov.get('lines', {}):
        if k not in used:
            print('override matched no line:', k)
json.dump(d, open(a.lyrics, 'w'), indent=1)
with open(a.js, 'w') as fjs:
    fjs.write('// lyrics.js: generated by tools/lyrics.py and tools/voices.py. Do not edit; re-run the tools.\n')
    fjs.write('const LYRICS = ' + json.dumps(d) + ';\n')
diff = [l for l in d['lines'] if not l['backing'] and l['voice'] and l['singer'] in ('F', 'M') and l['voice'] != l['singer']]
print('overrides (heard):', sum(1 for l in d['lines'] if l.get('heard')), 'lines')
print(f"{len(diff)} lines sung by a different voice than labelled:")
for l in diff:
    print(f"  {l['start']:7.2f}  {l['section']:12} labelled {l['singer']}, sung {l['voice']} (x{l['voiceConf']})  {l['text'][:50]}")
